// <auto-generated />
using System;
using BucketListTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BucketListTravel.Migrations
{
    [DbContext(typeof(BucketListTravelDbContext))]
    [Migration("20261001103136_SeedCatalog")]
    partial class SeedCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BucketListTravel.Data.Models.BucketListEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("BucketListEntries");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beach & Islands"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nature & Wildlife"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Culture & History"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cities & Food"
                        });
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Country = "Greece",
                            Description = "Whitewashed villages, volcanic beaches, and spectacular sunsets over the Aegean Sea.",
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff",
                            Name = "Santorini"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Country = "French Polynesia",
                            Description = "A turquoise lagoon surrounded by coral reefs and lush volcanic peaks.",
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
                            Name = "Bora Bora"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Country = "Italy",
                            Description = "Dramatic coastal cliffs, colorful villages, and clear Mediterranean waters.",
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077",
                            Name = "Amalfi Coast"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Country = "Canada",
                            Description = "Glacial lakes, alpine trails, and mountain scenery in the Canadian Rockies.",
                            ImageUrl = "https://images.unsplash.com/photo-1503614472-8c93d56e92ce",
                            Name = "Banff National Park"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Country = "Tanzania",
                            Description = "Vast plains and unforgettable wildlife encounters during the great migration.",
                            ImageUrl = "https://images.unsplash.com/photo-1516426122078-c23e76319801",
                            Name = "Serengeti National Park"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Country = "Ecuador",
                            Description = "Unique wildlife, volcanic landscapes, and extraordinary snorkeling opportunities.",
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5",
                            Name = "Galápagos Islands"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Country = "Argentina",
                            Description = "Remote wilderness with glaciers, granite peaks, and world-class trekking routes.",
                            ImageUrl = "https://images.unsplash.com/photo-1530789253388-582c481c54b0",
                            Name = "Patagonia"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Country = "Switzerland",
                            Description = "An alpine base for paragliding, hiking, skiing, and breathtaking mountain views.",
                            ImageUrl = "https://images.unsplash.com/photo-1531366936337-7c912a4589a7",
                            Name = "Interlaken"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Country = "New Zealand",
                            Description = "The adventure capital of New Zealand, surrounded by lakes and dramatic peaks.",
                            ImageUrl = "https://images.unsplash.com/photo-1469521669194-babb45599def",
                            Name = "Queenstown"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Country = "Japan",
                            Description = "Historic temples, traditional gardens, and seasonal Japanese culture.",
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
                            Name = "Kyoto"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Country = "Jordan",
                            Description = "An ancient city carved into rose-colored cliffs and reached through the Siq.",
                            ImageUrl = "https://images.unsplash.com/photo-1548786811-dd6e453ccca7",
                            Name = "Petra"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Country = "Peru",
                            Description = "A remarkable Inca citadel set high in the Andes above the Sacred Valley.",
                            ImageUrl = "https://images.unsplash.com/photo-1526392060635-9d6019884377",
                            Name = "Machu Picchu"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Country = "Spain",
                            Description = "Gaudí architecture, lively neighborhoods, Mediterranean beaches, and tapas.",
                            ImageUrl = "https://images.unsplash.com/photo-1539037116277-4db20889f2d4",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Country = "Türkiye",
                            Description = "A crossroads of continents known for its markets, mosques, and rich cuisine.",
                            ImageUrl = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200",
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Country = "United States",
                            Description = "Distinctive Creole food, jazz, and historic architecture along the Mississippi.",
                            ImageUrl = "https://images.unsplash.com/photo-1548013146-72479768bada",
                            Name = "New Orleans"
                        });
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.BucketListEntry", b =>
                {
                    b.HasOne("BucketListTravel.Data.Models.Destination", "Destination")
                        .WithMany("BucketListEntries")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Destination", b =>
                {
                    b.HasOne("BucketListTravel.Data.Models.Category", "Category")
                        .WithMany("Destinations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Photo", b =>
                {
                    b.HasOne("BucketListTravel.Data.Models.Destination", "Destination")
                        .WithMany("Photos")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Category", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("BucketListTravel.Data.Models.Destination", b =>
                {
                    b.Navigation("BucketListEntries");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
